[travis] use .travis.yml from python3_move branch

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -2,19 +2,33 @@ language: generic
 
 before_install:
  - git fetch --depth=1000 --tags origin master
- - alias python=python${TRAVIS_PYTHON_VERSION}
+ - alias python=python${PYMOR_PYTHON_VERSION}
+ - export PYTHON_X=python${PYMOR_PYTHON_VERSION}
+ # for some reason installing ptyhon-pytest does not install a /usr/bin/py.test-2.7 which we fake below
+ - export PY_TEST_X="${PYTHON_X} /usr/local/bin/py.test"
+ - export PIP_X=pip${PYMOR_PYTHON_MAJOR}
  - sudo add-apt-repository -y ppa:pymor/stable
- - sudo add-apt-repository -y ppa:fenics-packages/fenics
+ - sudo add-apt-repository -y ppa:fkrull/deadsnakes-python2.7
  - sudo apt-get update -qq
  # these are packages not on travis' whitelist/only in our ppa
- - sudo apt-get install -y -qq python-docopt python-pytest python-opengl python-distribute ipython python-pyside python-pyvtk python-mpi4py
- - for pkg in ipyparallel pytest-cov python-coveralls ; do sudo -E pip install ${pkg} ; done
+ - sudo apt-get install -y -qq python2.7 python-pytest python-docopt python-pytest python-opengl python-distribute ipython python-pyside python-mpi4py
+ - sudo apt-get install -y -qq python3-tk cython3 python3-pip python3.4-venv python3-docopt python3-pytest python3-opengl ipython3 python3-pyside python3-mpi4py
+ - for pkg in 3to2 https://bitbucket.org/pauloh/pyevtk/get/tip.tar.gz ipyparallel pytest-cov sympy python-coveralls ; do sudo -E ${PIP_X} install ${pkg} ; done
+ - sudo -E ${PIP_X} install -U pytest
+ # our exp. py3 packages are incompat. with the official repo
  # using aptitude here because it auto-fixes problems
- - sudo aptitude install -y -q dolfin-dev python-dolfin
- - python -c 'import  dolfin' || echo "import dolfin failed"
+ - |
+  if [ "${PYMOR_PYTHON_MAJOR}" == "3" ] ; then
+      sudo add-apt-repository -y ppa:pymor/fenics-py3
+      sudo aptitude install -y -q dolfin-dev python3-dolfin
+  else
+      sudo add-apt-repository -y ppa:fenics-packages/fenics
+      sudo aptitude install -y -q dolfin-dev python-dolfin
+  fi
+ - ${PYTHON_X} -c 'import  dolfin' || echo "import dolfin failed"
 
 install:
- - python setup.py build_ext -i
+ - ${PYTHON_X} setup.py build_ext -i
 
 sudo: required
 dist: trusty
@@ -22,17 +36,16 @@ dist: trusty
 script:
  - |
   if [ "${PYTEST_MARKER}" == "PIP_ONLY" ] ; then
-    virtualenv piptest
+    virtualenv --python=${PYTHON_X} piptest
     source piptest/bin/activate
     # this fails on PRs, so skip it
-    [[ "${TRAVIS_PULL_REQUEST}" != "false" ]] || pip install git+https://github.com/${TRAVIS_REPO_SLUG}.git@${TRAVIS_COMMIT}
+    [[ "${TRAVIS_PULL_REQUEST}" != "false" ]] || ${PIP_X} install git+https://github.com/${TRAVIS_REPO_SLUG}.git@${TRAVIS_COMMIT}
   elif [ "${PYTEST_MARKER}" == "MPI" ] ; then
     export PYTHONPATH=$(pwd)/src
-    xvfb-run -a mpirun -n 2 python src/pymortests/mpi_run_demo_tests.py
+    xvfb-run -a mpirun -n 2 ${PYTHON_X} src/pymortests/mpi_run_demo_tests.py
   else
-    export PYTHONPATH=$(pwd)/src
     # this runs in pytest in a fake, auto numbered, X Server
-    xvfb-run -a py.test -k "${PYTEST_MARKER}"
+    xvfb-run -a ${PY_TEST_X} -k "${PYTEST_MARKER}"
   fi
 
 notifications:
@@ -47,22 +60,24 @@ branches:
   except:
     - gh-pages
 
-env:
-  - PYTEST_MARKER="not slow"
-  - PYTEST_MARKER="slow"
-  - PYTEST_MARKER="PIP_ONLY"
-  - PYTEST_MARKER="MPI"
-
 addons:
   apt:
     packages:
     - debhelper
     - python-pip
     - python-markupsafe
+    - python3-markupsafe
     - git
     - cython
     - xvfb
     - libopenmpi-dev
+    - python3-numpy
+    - python3-sphinx
+    - python3-scipy
+    - python3-matplotlib
+    - python3-dev
+    - python3-six
+    - python-six
     - python-virtualenv
     - python-numpy
     - python-sphinx
@@ -84,4 +99,13 @@ addons:
 
 os:
   - linux
+
+env:
+  global: PYMOR_PYTHON_MAJOR=3 PYMOR_PYTHON_VERSION=3.4
+  matrix:
+  - PYTEST_MARKER="not slow"
+  - PYTEST_MARKER="slow"
+  - PYTEST_MARKER="PIP_ONLY"
+  - PYTEST_MARKER="MPI"
+  - PYMOR_PYTHON_MAJOR=2 PYMOR_PYTHON_VERSION=2.7 PYTEST_MARKER="not slow"
 
