[travis/setup] rewire to use "native" python setup again

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,19 +1,16 @@
-language: generic
+language: python
 
 git:
   depth: 1000
 
 before_install:
- - alias python=python${PYMOR_PYTHON_VERSION}
- - export PYTHON_X=python${PYMOR_PYTHON_VERSION}
- # for some reason installing ptyhon-pytest does not install a /usr/bin/py.test-2.7 which we fake below
- - export PY_TEST_X="${PYTHON_X} /usr/local/bin/py.test"
- - export PIP_X=pip${PYMOR_PYTHON_MAJOR}
+ - export PYTHON_X=python
+ - export PY_TEST_X="py.test"
+ - export PIP_X=pip
  - sudo add-apt-repository -y ppa:pymor/stable
  # our exp. py3 packages are incompat. with the official repo
- # using aptitude here because it auto-fixes problems
  - |
-  if [ "${PYMOR_PYTHON_MAJOR}" == "3" ] ; then
+  if [ "${TRAVIS_PYTHON_VERSION}" == "3.4" ] ; then
       sudo add-apt-repository -y ppa:pymor/fenics-py3
       sudo aptitude update
       sudo aptitude install -y -q libslepc3.4.2-dev libhdf5-openmpi-dev python3-zmq python3-dev python3-dolfin python3-mpi4py python3-tk cython3 python3-pip python3.4-venv python3-docopt python3-pytest python3-opengl ipython3 python3-pyside python3-mpi4py python3-sympy python3-scipy
@@ -22,21 +19,12 @@ before_install:
       sudo aptitude update
       sudo aptitude install -y -q libslepc3.4.2-dev libhdf5-openmpi-dev python-zmq python-dev python-dolfin python-mpi4py python2.7 python-pytest python-docopt python-pytest python-opengl python-distribute ipython python-pyside python-mpi4py
   fi
-  if [ "${PYMOR_PYTHON_VERSION}" == "3.5" ] ; then
-    sudo add-apt-repository -y ppa:fkrull/deadsnakes
-    sudo aptitude update
-    sudo aptitude install -yq python3.5-dev python3.5-minimal tcl-dev tk-dev
-    # remove incompat package and reinstall with updated pip
-    sudo aptitude remove -y python3-numpy python3-pyside
-    wget -O /tmp/get-pip.py https://bootstrap.pypa.io/get-pip.py && sudo python3.5 /tmp/get-pip.py
-    export PIP_X=/usr/local/bin/pip3.5
-    sudo -E ${PIP_X} install -U numpy scipy setuptools distribute matplotlib sympy sphinx pyopengl ipyparallel zmq
-  fi
  - ${PYTHON_X} -c 'import  dolfin' || echo "import dolfin failed"
- - for pkg in 3to2 https://bitbucket.org/pauloh/pyevtk/get/tip.tar.gz ipyparallel pytest-cov python-coveralls ; do sudo -E ${PIP_X} install ${pkg} ; done
- - sudo -E ${PIP_X} install -U pytest check-manifest
 
 install:
+ - ${PIP_X} install -r requirements.txt
+ - ${PIP_X} install -r requirements-travis.txt
+ - ${PIP_X} install -r requirements-optional.txt || echo "Some optional modules failed to install"
  - ${PYTHON_X} setup.py build_ext -i
 
 sudo: required
@@ -116,20 +104,17 @@ os:
   - linux
 
 env:
-  global: PYMOR_PYTHON_MAJOR=3 PYMOR_PYTHON_VERSION=3.4
   matrix:
   - PYTEST_MARKER="not slow"
   - PYTEST_MARKER="slow"
   - PYTEST_MARKER="PIP_ONLY"
   - PYTEST_MARKER="MPI"
-  - PYMOR_PYTHON_MAJOR=2 PYMOR_PYTHON_VERSION=2.7 PYTEST_MARKER="not slow"
-  - PYMOR_PYTHON_MAJOR=2 PYMOR_PYTHON_VERSION=2.7 PYTEST_MARKER="slow"
-  - PYMOR_PYTHON_MAJOR=2 PYMOR_PYTHON_VERSION=2.7 PYTEST_MARKER="PIP_ONLY"
-  - PYMOR_PYTHON_MAJOR=2 PYMOR_PYTHON_VERSION=2.7 PYTEST_MARKER="MPI"
-  - PYMOR_PYTHON_MAJOR=3 PYMOR_PYTHON_VERSION=3.5 PYTEST_MARKER="not slow"
-  - PYMOR_PYTHON_MAJOR=3 PYMOR_PYTHON_VERSION=3.5 PYTEST_MARKER="slow"
-  - PYMOR_PYTHON_MAJOR=3 PYMOR_PYTHON_VERSION=3.5 PYTEST_MARKER="PIP_ONLY"
-  - PYMOR_PYTHON_MAJOR=3 PYMOR_PYTHON_VERSION=3.5 PYTEST_MARKER="MPI"
+
+python:
+    # system packages enable us to use fenics debs
+    - "2.7_with_system_site_packages"
+    - "3.4_with_system_site_packages"
+    - "3.5"
 
 cache:
     pip
